config/routes.rb
Rails.application.routes.draw do

  root 'merchandise_managements#index'
  resources :merchandise_managements do
    resources :records, only: [:create, :destroy]
  end

end

app/models/history.rb
class History < ActiveRecord::Base
  # belongs_to :merchandise_managements
  def date
  end
  
end

app/models/merchandise_management.rb
class MerchandiseManagement < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader

  validates :number, presence: true
  validates_uniqueness_of :number, :message => "は既に登録されています"

  has_many:records

  scope :search, ->(keyword = nil) do
    if keyword.present?
      sql = <<-EOS
        `name`    LIKE :keyword OR
        `size`    LIKE :keyword OR
        `color`   LIKE :keyword OR
        `number`  LIKE :keyword OR
        `maker`   LIKE :keyword
      EOS
      where(sql, keyword: "%#{keyword}%")
    end
  end

  def quantity
    self.records.sum(:q)
  end
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :merchandise_management
  validates :in, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def new
  end
  
  def index
    @histories = History.all
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
<<<<<<< HEAD
=======
  def new
  end
  
  def index
    @histories = History.all
  end
>>>>>>> cc1a8eab28106116983924865edff39af9371522
end

app/controllers/merchandise_managements_controller.rb
class MerchandiseManagementsController < ApplicationController
  before_action :set_merchandise_management, only: [:show, :edit, :update, :destroy]

  def index
    @merchandise_managements = MerchandiseManagement.search(params[:q])
  end

  def show
  end

  def new
    @merchandise_management = MerchandiseManagement.new
  end

  def edit
  end

  def create
    @merchandise_management = MerchandiseManagement.new(merchandise_management_params)
    respond_to do |format|
      if @merchandise_management.save
        format.html { redirect_to @merchandise_management, notice: 'Merchandise management was successfully created.' }
        format.json { render :show, status: :created, location: @merchandise_management }
      else
        format.html { render :new }
        format.json { render json: @merchandise_management.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @merchandise_management.update(merchandise_management_params)
        format.html { redirect_to @merchandise_management, notice: 'Merchandise management was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchandise_management }
      else
        format.html { render :edit }
        format.json { render json: @merchandise_management.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @merchandise_management.destroy
    respond_to do |format|
      format.html { redirect_to merchandise_managements_url, notice: 'Merchandise management was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_merchandise_management
      @merchandise_management = MerchandiseManagement.find(params[:id])
    end

    def merchandise_management_params
      params.require(:merchandise_management).permit(:picture, :name, :size, :color, :number, :maker, :price)
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  def create
    @merchandise_management = MerchandiseManagement.find(params[:merchandise_management_id])
    @record = @merchandise_management.records.create(record_params)
    redirect_to merchandise_management_path(@merchandise_management.id)
  end
  
  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to merchandise_management_path(params[:merchandise_management_id])
  end

  private
    def record_params
      params[:record].permit(:in, :q)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def number_image_tag(merchandise_management)
    image_tag "#{merchandise_management.number}.jpg"
  end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/merchandise_managements_helper.rb
module MerchandiseManagementsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/entries/index.html.erb
<h1>Histories#new</h1>

app/views/entries/new.html.erb
<h1>Histories#new</h1>
<p>Find me in app/views/histories/new.html.erb</p>

app/views/histories/index.html.erb
<h1>在庫履歴</h1>

app/views/histories/new.html.erb
<h1>入出庫登録</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "AMS" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
    
   
  </head>
  <body>
  
   
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">

      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">AMS</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "TOP", root_path %></li>
          </ul>
          <ul class="nav navbar-nav">
            <li>
              <%= form_tag merchandise_managements_path, method: :get, class: "navbar-form" do %>
                <div class="form-group">
                  <div class="input-group">
                    <%= search_field_tag "q", params[:q], class: "form-control", placeholder: "キーワード" %>
                    <span class="input-group-btn">
                      <button type="submit" class="btn btn-info">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        検索
                      </button>
                    </span>
                  </div>
                </div>
              <% end %>
            </li>
          </ul>
          <div class="nav navbar-nav navbar-right logo">&nbsp;</div>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

<div class="container">
      <div class="row">
        <div class="col-md-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
<!--       <div class="col-md-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "TOP", "#"  %></li>
              <li><%= link_to "商品一覧", "#"  %></li>
              <li><%= link_to "商品検索", "#"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/spa  -->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/merchandise_managements/_form.html.erb
<%= form_for(@merchandise_management, html: { multipart: true }) do |f| %>
  <% if @merchandise_management.errors.any? %>
    <div id="error_explanation">
     <h2><%= pluralize(@merchandise_management.errors.count, "error") %> prohibited this merchandise_management from being saved:</h2>
   <ul>
      <% @merchandise_management.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <span class="picture">
    <%= f.label :参照をクリックして商品画像を登録してください %><br>
    <%= f.file_field :picture %>
  </span>
  <br>

 <%= f.label :商品名を選択してください %><br>
  <%= f.select :name, ['Ｔシャツ', 'アウター', 'パンツ', 'その他'] %>

<br><br>

  <div class="field">
    <%= f.label :サイズを入力してください %><br>
        S<%= f.radio_button :size,'S' %>&nbsp;&nbsp;
        M<%= f.radio_button :size,'M' %>&nbsp;&nbsp;
        L<%= f.radio_button :size,'L' %>&nbsp;&nbsp;
        LL<%= f.radio_button :size,'LL' %>
  </div>
  
  <%= f.label :カラーを選択してください %><br>
  <%= f.select :color, %w(white black blue gray その他) %>

<br><br>
  <div class="field">
    <%= f.label :型番を入力してください %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :メーカーを入力してください %><br>
    <%= f.text_field :maker %>
  </div>
  <div class="field">
    <%= f.label :単価を入力してください %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/merchandise_managements/edit.html.erb
<h1>商品情報変更</h1>

<%= render 'form' %>

<%= link_to '戻る', merchandise_managements_path, class: "btn btn-info" %>

app/views/merchandise_managements/index.html.erb
<p id="notice"><%= notice %></p>

<h1><div align="left">商品管理</div></h1>

<!--

<div class="btn-group" data-toggle="buttons">
  <label class="btn btn-primary active">
    <input type="checkbox" autocomplete="off" checked>画像
  </label>
  <label class="btn btn-primary">
    <input type="checkbox" autocomplete="off">商品
  </label>
  <label class="btn btn-primary">
    <input type="checkbox" autocomplete="off">サイズ
  </label>
  <label class="btn btn-primary active">
    <input type="checkbox" autocomplete="off">カラー
  </label>
  <label class="btn btn-primary">
    <input type="checkbox" autocomplete="off">型番
  </label>
  <label class="btn btn-primary">
    <input type="checkbox" autocomplete="off">メーカー
  </label>
  <label class="btn btn-primary">
    <input type="checkbox" autocomplete="off">単価
  </label>
  <label class="btn btn-primary">
    <input type="checkbox" autocomplete="off">数量
  </label>
  <label class="btn btn-primary">
    <input type="checkbox" autocomplete="off">日付
  </label>
</div> -->



<br>
</li><%= link_to '新規追加', new_merchandise_management_path, class: "btn btn-success" %></br>
<div class ="container" style="padding:5px 0"></br>

<table class ="table table-striped table-bordered table-condensed">
  <thead>
    <tr class="warning">
      <th>商品画像</th>
      <th>商品名</th>
      <th>サイズ</th>
      <th>カラー</th>
      <th>型番</th>
      <th>メーカー</th>
      <th>単価</th>
      <th>数量</th>
      <th></th>      
    </tr>
  </thead>

  <tbody>
    <% @merchandise_managements.each do |merchandise_management| %>
      <tr>
        <td>
          <% if merchandise_management.picture? %>
            <%= link_to merchandise_management.picture.to_s, class: "fancybox" do %>
              <%= image_tag merchandise_management.picture, style: "max-width:100px;max-height:100px" %>
            <% end %>
          <% end %>
        </td>
        <td><%= merchandise_management.name %></td>
        <td><%= merchandise_management.size %></td>
        <td><%= merchandise_management.color %></td>
        <td><%= merchandise_management.number %></td>
        <td><%= merchandise_management.maker %></td>
        <td><%= merchandise_management.price %></td>
        <td><%= merchandise_management.quantity %></td>
        <td>
          <%= link_to '商品詳細', merchandise_management, class: "btn btn-info" %>
          <%= link_to '編集', edit_merchandise_management_path(merchandise_management), class: "btn btn-success" %>
          <%= link_to '削除', merchandise_management, method: :delete, data: { confirm: '削除してもよろしいですか？' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/merchandise_managements/new.html.erb
<h1><div align="left">新規追加</div></h1><br>

<%= render 'form' %>

<%= link_to '戻る', merchandise_managements_path, class: "btn btn-info" %>

app/views/merchandise_managements/show.html.erb
<p id="notice"><%= notice %></p>
<h1><div align="left">商品詳細</div></h1>
<br>

<table class ="table table-striped table-bordered table-condensed">
  <thead>
    <tr class="warning">
      <th>商品画像</th>
      <th>商品名</th>
      <th>サイズ</th>
      <th>カラー</th>
      <th>型番</th>
      <th>メーカー</th>
      <th>単価</th>
      <th>数量</th>
      <th colspan="3"></th>      
    </tr>
  </thead>
</table>



<p>
  <strong>商品画像:</strong>
  <%= link_to @merchandise_management.picture.to_s, class: "fancybox" do %>
    <%= image_tag @merchandise_management.picture, style: "max-width:100px;max-height:100px" %>
  <% end %>
</p>

<p>
  <strong>商品名:</strong>
  <%= @merchandise_management.name %>
</p>

<p>
  <strong>サイズ:</strong>
  <%= @merchandise_management.size %>
</p>

<p>
  <strong>カラー:</strong>
  <%= @merchandise_management.color %>
</p>

<p>
  <strong>型番:</strong>
  <%= @merchandise_management.number %>
</p>

<p>
  <strong>メーカー:</strong>
  <%= @merchandise_management.maker %>
</p>

<p>
  <strong>単価:</strong>
  <%= @merchandise_management.price %>
</p>

<p>
  <strong>数量:</strong>
  <%= @merchandise_management.quantity %>
</p>


<%= link_to '商品情報変更', edit_merchandise_management_path(@merchandise_management), class: "btn btn-success" %>
<%= link_to '商品管理', merchandise_managements_path, class: "btn btn-info" %>


<div class="container" style="padding:20px 0">

<table class= "table table-striped table-bordered table-hover table-condensed" >
<thead><tr class="warning"><th>発生日&nbsp;&nbsp;(8桁入力&nbsp;&nbsp;記入例：20160527)</th><th>増減数量&nbsp;(個)</th><th>削除</th></tr>
</thead>

<tbody>
<%= form_for [@merchandise_management, @merchandise_management.records.build], url: merchandise_management_records_path(@merchandise_management) do |f| %>
 <tr>
  <td><%= f.date_select :in %></td>
  <td><%= f.text_field :q %></td>
  <td><%= f.submit class: "btn btn-success" %></td>
 </tr> 
<% end %> 

<% @merchandise_management.records.each do |record| %>
  <% unless record.new_record? %>
  <tr>
    <td><%= record.in %></td><td><%= record.q %></td>
    <td><%= link_to '削除', merchandise_management_record_path(record.merchandise_management_id, record.id), method: :delete, data: { confirm: '削除しますが、よろしいでしょか?' }, class: "btn btn-danger" %></td>
  </tr>
  <% end %>
<% end %>

</tbody>
</table>



</div>